project:
  type: website

website:
  title: "SSD_NIS Technical Working Goup"
  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: sudancrisis.qmd
        text: Sudan Crisis
      - href: program.qmd
        text: Program Updates
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    echo: false
    warning: FALSE
    message: FALSE



